id: AA9594480
title: CXXIX_Verses 51-57
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.143030
  last_modified_at: 2022-03-01 23:21:37.143032
