id: AA9594480
title: CXXXIII_Verses 81-83
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.217984
  last_modified_at: 2022-03-01 23:21:37.217987
