id: AA9594480
title: CX_Verses 11-16
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.284170
  last_modified_at: 2022-03-01 23:21:37.284173
