id: AA9594480
title: CXXXII_Verses 81-82
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.239094
  last_modified_at: 2022-03-01 23:21:37.239097
