id: AA9594480
title: CIX_Verses 11-19
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.003090
  last_modified_at: 2022-03-01 23:21:37.003096
