id: AA9594480
title: CXXVI_Verses 11-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.181516
  last_modified_at: 2022-03-01 23:21:37.181519
