id: AA9594480
title: CXVI_Verses 21-24
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.095052
  last_modified_at: 2022-03-01 23:21:37.095055
