id: AA9594480
title: CV_Verses 21-27
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.043875
  last_modified_at: 2022-03-01 23:21:37.043879
