id: AA9594480
title: CIV_Verses 31-38
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:36.995177
  last_modified_at: 2022-03-01 23:21:36.995179
