id: AA9594480
title: CXXXI_Verses 21-30
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.247007
  last_modified_at: 2022-03-01 23:21:37.247010
