id: AA9594480
title: CXI_Verses 11-15
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.073190
  last_modified_at: 2022-03-01 23:21:37.073193
