id: AA9594480
title: CXXX_Verses 51-52
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.271155
  last_modified_at: 2022-03-01 23:21:37.271157
