id: AA9594480
title: CXVII_Verses 11-12
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.086662
  last_modified_at: 2022-03-01 23:21:37.086665
