id: AA9594480
title: CXXXIII_Verses 71-80
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.215962
  last_modified_at: 2022-03-01 23:21:37.215966
