id: AA9594480
title: CXXV_Verses 11-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.190306
  last_modified_at: 2022-03-01 23:21:37.190309
