id: AA9594480
title: CXVIII_Verses 21-21F
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.081611
  last_modified_at: 2022-03-01 23:21:37.081615
