id: AA9594480
title: CXXIII_Verses 21-26
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.111245
  last_modified_at: 2022-03-01 23:21:37.111248
