id: AA9594480
title: CXX_Verses 21-22
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.278617
  last_modified_at: 2022-03-01 23:21:37.278620
