id: AA9594480
title: CXIII_Verses 11-18
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.049907
  last_modified_at: 2022-03-01 23:21:37.049910
