id: AA9594480
title: CXVII_Verses 1-10
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.084766
  last_modified_at: 2022-03-01 23:21:37.084769
