id: AA9594480
title: CXXVII_Verse 41
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.162253
  last_modified_at: 2022-03-01 23:21:37.162256
