id: AA9594480
title: CII_Verses 1-10
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:36.977064
  last_modified_at: 2022-03-01 23:21:36.977070
