id: AA9594480
title: CXXIX_Verses 21-30
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.135043
  last_modified_at: 2022-03-01 23:21:37.135046
