id: AA9594480
title: CI_Verses 41-42
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.018034
  last_modified_at: 2022-03-01 23:21:37.018037
