id: AA9594480
title: CXXXII_Verses 41-50
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:21:37.231339
  last_modified_at: 2022-03-01 23:21:37.231343
